
<?php foreach($catIdBooks as $catIdBook): ?>
    <article class="articleCat">
        <img src="../public/uploads/images_Covers/<?= htmlspecialchars($catIdBook['art_image']) ?>" alt="couverture de livres" class="welcome">
        <h2><?= htmlspecialchars($catIdBook['art_title']) ?></h2>
        <p>Auteur: <?= htmlspecialchars($catIdBook['art_writer']) ?></p>
        <p>Editeur: <?= htmlspecialchars($catIdBook['art_editor']) ?></p>
        <p>Prix: <?= htmlspecialchars($catIdBook['art_price']) ?> €</p>
        <p>Catégorie: <?= htmlspecialchars($catIdBook['cat_title']) ?></p>
        <p>ISBN: <?= htmlspecialchars($catIdBook['art_ref']) ?></p>
        <p><?= htmlspecialchars($catIdBook['art_nbre_of_pages']) ?> pages</p>
        <p><?= htmlspecialchars($catIdBook['art_description']) ?></p>
        <p>Quantités en magasin: <?= htmlspecialchars($catIdBook['art_quantity']) ?></p>
        <br>
       
           
        <?php if( isset ($_SESSION["user"]) && $_SESSION["user"]["role"] == 1): ?> <!-- 1= admin -->
         <div class="button">
            <a href="index.php?route=modifBook&id=<?= htmlspecialchars($catIdBook['art_id']) ?>">MODIFIER L'ARTICLE</a>
        </div>
         <div class="button">
            <a href="index.php?route=deleteArticle&id=<?= htmlspecialchars($catIdBook['art_id']) ?>&cat=<?= htmlspecialchars($catIdBook['cat_id']) ?>">SUPPRIMER L'ARTICLE</a>
        </div>    
        <?php endif; ?>
    </article>
<?php endforeach; ?>
    