<fieldset>
    <legend>Connexion</legend>
    
         
         <?php require_once('_errors.phtml');?>
         <?php require_once('_valids.phtml');?>
        
                    
        <form enctype="multipart/form-data" action="index.php?route=connect&ref=connect" method="POST">
            <h2>Renseigner les informations suivantes pour vous connecter:</h2><br>
            
            <label for="email">Email</label>
            <input id="email" type="text" name="email">
    
            <label for="user_password">Entrez votre mot de passe</label>
            <input id="user_password" type="password" name="password">
    
            <button id="eyes1"><i id="eyesImag1" class="fa-solid fa-eye-slash"></i></button>
         
            <button type="submit" class="log"><span>Se connecter</span></button>
          
        </form>
</fieldset>


