   <div class="foot_contain">
        <div class="foot block_info">
            <strong>Nos informations</strong>
            <ul class="foot_infos">
                <li><a href="index.php?route=cgv">CGV</a></li>
                <li><a href="https://goo.gl/maps/u3oECgyX1EYbPw5D6" target="_blank">Où nous trouver</a></li>
            </ul>
        </div>
        <div class="foot block_contact">
            <strong>Nous contacter</strong>
                    <p>📞 04-42-27-44-68</p>
                    <p>📨 momijilib@orange.fr</p>
                    <p>🏠 23 rue des érables <br> 13100 Aix-en-Provence</p>
        </div>
        
        <div class="foot block_social">
            <strong>Nos réseaux sociaux</strong>
            <ul class="foot_infos">
                <li><a href="https://www.facebook.com/3WAcademy/"><i class="fa-brands fa-facebook"></i>Facebook</a></li>
                <li><a href="https://instagram.com/3w_academy_fr/"><i class="fa-brands fa-instagram"></i>Instagram</a></li>
                <li><a href="https://twitter.com/3wacademy"><i class="fa-brands fa-twitter"></i>Twitter</a></li>
            </ul>
        </div>
        
        <div class="foot block_planning">
            <strong>Horaires de la librairie</strong>
            <ul class="foot_infos">
                <li>❌ Lundi fermé</li>
                <li>👍 Mardi 9h30/19h00</li>
                <li>👍 Mercredi 9h30/19h00</li>
                <li>👍 Jeudi 9h30/19h00</li>
                <li>👍 Vendredi 9h30/19h00</li>
                <li>👍 Samedi 9h00/19h30</li>
                <li>❌ Dimanche fermé</li>
            </ul>
        </div>
    </div>