

    
<?php if(isset($_SESSION['message'])) : ?>
     <p class="refBasket"><?= $_SESSION['message'] ?></p>
     <?php unset($_SESSION['message']) ?>
<?php endif; ?>

    <div class="article">
        <?php foreach($books as $book): ?>
        <article>
            <img src="../public/uploads/images_Covers/<?= htmlspecialchars($book['art_image']) ?>" alt="couverture de livres" class="welcome">
            <h2><?= htmlspecialchars($book['art_title']) ?></h2>
            <p>Auteur: <?= htmlspecialchars($book['art_writer']) ?></p>
            <p>Editeur: <?= htmlspecialchars($book['art_editor']) ?></p>
            <p>Prix: <?= htmlspecialchars($book['art_price']) ?> €</p>
            <p>Catégorie: <?= htmlspecialchars($book['cat_title']) ?></p>
            <p>ISBN: <?= htmlspecialchars($book['art_ref']) ?></p>
            <p><?= htmlspecialchars($book['art_nbre_of_pages']) ?> pages</p>
            <p><?= htmlspecialchars($book['art_description']) ?></p>
            <p>Quantités en magasin: <?= htmlspecialchars($book['art_quantity']) ?></p><br>
        </article>
        <?php endforeach; ?>
    </div>
